#!/bin/bash

if [ -z "$1" ]; then
    echo "No content supplied"
    exit 1
fi

# Get filename representing current date
NOW=`date +"%Y-%m-%d"`
NOW=$NOW.txt
NOW_TIME=`date +"%H:%M"`

WORK_DIR="$HOME/.br"
WORK_FILE="$WORK_DIR/$NOW"

mkdir -p $WORK_DIR

echo "$NOW_TIME - $*" >> $WORK_FILE
